# Generated by Django 6.0.7 on 2026-07-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
